[target.xtensa-esp32s3-none-elf]
runner = "probe-rs run --chip=esp32s3 --preverify --always-print-stacktrace --no-location --catch-hardfault"

[env]

[build]
target = "xtensa-esp32s3-none-elf"

[target.'cfg(all(target_arch = "xtensa", target_env = "espidf"))']
rustflags = [
    "-C", "link-arg=-Tesp32s3_memory.ld",
]

[unstable]
build-std = ["alloc", "core"]
